"""Данные таблицы 4.1 (ручное тестирование) и соответствие автотестам."""

MANUAL_TEST_ROWS = [
    (
        1,
        "Регистрация (отключена)",
        "POST /api/auth/register с fullName, email, password в JSON.",
        "Ответ 403, сообщение о запрете регистрации.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_01_register_disabled",
    ),
    (
        2,
        "Подтверждение регистрации (отключено)",
        "POST /api/auth/verify-register с произвольным телом JSON.",
        "Ответ 403.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_02_verify_register_disabled",
    ),
    (
        3,
        "Публичное приглашение клиента",
        "POST /api/clients/{id}/invite-link (менеджер), затем GET /api/client-invite/{token} без Authorization.",
        "Ответ 200, поля clientName, managerName, canonicalUrl.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_03_public_client_invite",
    ),
    (
        4,
        "Аутентификация менеджера",
        "POST /api/auth/login: email manager1@crm.by, password 1234 (или user_2@test.crm.local после seed).",
        "Ответ 200, поля token и user.role=manager.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_04_manager_login",
    ),
    (
        5,
        "Аутентификация администратора",
        "POST /api/auth/login: admin@crm.by / 1234 (или user_1@test.crm.local).",
        "Ответ 200, user.role=admin.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_05_admin_login",
    ),
    (
        6,
        "Получение списка клиентов",
        "GET /api/clients с JWT менеджера или заголовками x-user-role/x-user-id.",
        "Массив клиентов только своего managerId.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_06_list_clients_manager",
    ),
    (
        7,
        "Получение карточки клиента",
        "GET /api/clients/{id} с правами менеджера-владельца.",
        "Ответ 200, объект клиента.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_07_get_client_by_id",
    ),
    (
        8,
        "Создание клиента",
        "POST /api/clients с name, phone, email.",
        "Ответ 201, managerId подставлен автоматически.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_08_create_client",
    ),
    (
        9,
        "Создание сделки",
        "POST /api/deals с title, clientId, stage.",
        "Ответ 201, объект сделки.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_09_create_deal",
    ),
    (
        10,
        "Создание задачи CRM",
        "POST /api/tasks с title, status, priority, dueDate.",
        "Ответ 201, объект задачи.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_10_create_task",
    ),
    (
        11,
        "Сводка панели управления (менеджер)",
        "GET /api/dashboard/overview от менеджера.",
        "role=manager, metrics, alerts.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_11_dashboard_manager",
    ),
    (
        12,
        "Сводка панели управления (администратор)",
        "GET /api/dashboard/overview от admin.",
        "role=admin, managerHealth.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_12_dashboard_admin",
    ),
    (
        13,
        "Получение списка звонков",
        "GET /api/calls менеджером.",
        "Массив звонков по своим клиентам.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_13_list_calls",
    ),
    (
        14,
        "Создание видеосессии",
        "POST /api/video-sessions с clientId (менеджер).",
        "Ответ 201, sessionId, guestToken, joinUrl.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_14_create_video_session",
    ),
    (
        15,
        "Метаданные входа гостя в видеозвонок",
        "GET /api/video-sessions/join/{guestToken} без JWT.",
        "Ответ 200, подсказка для join.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_15_video_join_meta",
    ),
    (
        16,
        "Список пользователей (администратор)",
        "GET /api/users с admin; менеджер — 403.",
        "Массив пользователей без password.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_16_list_users_admin",
    ),
    (
        17,
        "Создание менеджера",
        "POST /api/users с fullName, email, password (admin).",
        "Ответ 201, role=manager.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_17_create_manager_user",
    ),
    (
        18,
        "Удаление задачи",
        "DELETE /api/tasks/{id}.",
        "Ответ 200, запись удалена.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_18_delete_task",
    ),
    (
        19,
        "Ссылка приглашения клиента",
        "POST /api/clients/{id}/invite-link (менеджер).",
        "Ответ 201, token, url, expiresAt.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_19_client_invite_link",
    ),
    (
        20,
        "Создание звонка (администратор)",
        "POST /api/calls от admin с recordingUrl; менеджер — 403.",
        "201 или 400 при отсутствии файла; менеджер — 403.",
        "test_calls_manager_restrictions.py::TestCallsManagerRestrictions::test_admin_can_still_create_call",
    ),
    (
        21,
        "Загрузка аудиозаписи",
        "POST /api/uploads/voice multipart (admin).",
        "Файл в uploads/voice.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_21_upload_voice_optional",
    ),
    (
        22,
        "Привязка записи к звонку",
        "PUT /api/calls/{id} с recordingUrl (admin).",
        "Обновлённый звонок.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_22_update_call_recording_optional",
    ),
    (
        23,
        "Профиль текущего пользователя",
        "GET /api/auth/me с JWT.",
        "fullName, email, role без password.",
        "test_functional_table_4_1.py::TestFunctionalTable41::test_23_auth_me",
    ),
    (
        24,
        "Проверка работоспособности API",
        "GET /api/health.",
        '{"status":"ok"}.',
        "test_functional_table_4_1.py::TestFunctionalTable41::test_24_health",
    ),
]

MANUAL_HEADERS = [
    "№",
    "Функция web-приложения",
    "Описание тестирования (действие)",
    "Ожидаемый результат",
    "Итог тестирования",
    "Дата",
    "Исполнитель",
]

AUTO_HEADERS = [
    "№",
    "Функция web-приложения",
    "Автоматический тест (pytest)",
    "Файл",
    "Статус (CI/локально)",
]
